POST http://localhost:3000/RetNumberController/retNumberRoute
Content-Type: application/json

{
  "value": 40
}
###

GET http://localhost:3000/RetItemController/1


###

### CREATE
POST http://localhost:3000/items
Content-Type: application/json

{
  "name": "Alpha",
  "description": "first",
  "quantity": 2
}

### LIST
GET http://localhost:3000/items

### GET ONE
GET http://localhost:3000/items/27

### UPDATE
PATCH http://localhost:3000/items/1
Content-Type: application/json

{
  "name": "Alpha v2",
  "quantity": 10
}

### DELETE
DELETE http://localhost:3000/items/1

### GET ONE (expect 404)
GET http://localhost:3000/items/4



###
POST http://localhost:3000/jobs/enqueue
Content-Type: application/json

{
  "userId": 42,
  "payload": "test payload"
}

###

POST http://localhost:3000/testEncrypt/insert
Content-Type: application/json

{
  "name": "test payload",
  "description": "some text"
}

###
# Auth test

GET http://localhost:3000/items

###

GET http://localhost:3000/items
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbjEyMyIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3QvIiwiYXVkIjoiYXBpOi8vZGVmYXVsdCIsImh0dHBzOi8veW91cmFwcC5leGFtcGxlLmNvbS9yb2xlcyI6WyJhZG1pbiJdLCJpYXQiOjE3NTU3NTc4ODcsImV4cCI6MTc1NTc3MjI4N30.69iqBgSOUmj41B9Ms46ybYYY5CFwOGfHgzgKORHv5sQ


###

POST http://localhost:3000/items
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbjEyMyIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3QvIiwiYXVkIjoiYXBpOi8vZGVmYXVsdCIsImh0dHBzOi8veW91cmFwcC5leGFtcGxlLmNvbS9yb2xlcyI6WyJhZG1pbiJdLCJpYXQiOjE3NTU3NTc4ODcsImV4cCI6MTc1NTc3MjI4N30.69iqBgSOUmj41B9Ms46ybYYY5CFwOGfHgzgKORHv5sQ
Content-Type: application/json

{
  "name": "Test item from admin"
}


###
 //Non-admin token [user]
GET http://localhost:3000/items
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyMTIzIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdC8iLCJhdWQiOiJhcGk6Ly9kZWZhdWx0IiwiaHR0cHM6Ly95b3VyYXBwLmV4YW1wbGUuY29tL3JvbGVzIjpbInVzZXIiXSwiaWF0IjoxNzU1NzU4NDYxLCJleHAiOjE3NTU3NjIwNjF9.5XjhlD5MLkTDWED44b07FnBZoVjjBRB3KJ_rn6F6phM