### @name getToken
POST https://dev-6qkc8ccshfymghci.us.auth0.com/oauth/token
content-type: application/json

{
  "client_id": "74DAH4jnGjOwTjvA1nZk0byq9FDwBq0u",
  "client_secret": "QYanvgxkZf3KmJOk6cT0OhKmNVn_AehpbKVCnMnRtajIFExKarkuJnQrE-cLaEqF",
  "audience": "https://nest-demo-api",
  "grant_type": "client_credentials"
}

###

# Use access_token from the previous response
GET http://localhost:3000/protected
Accept: application/json
Authorization: Bearer {{getToken.response.body.$.access_token}}

###
GET http://localhost:3000/protected
Accept: application/json
Authorization: Bearer eyJhBADDATAbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlRIUzdCVUh4WTdDbThMUzlQU0dtdSJ9.eyJpc3MiOiJodHRwczovL2Rldi02cWtjOGNjc2hmeW1naGNpLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiI3NERBSDRqbkdqT3dUanZBMW5aazBieXE5RkR3QnEwdUBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9uZXN0LWRlbW8tYXBpIiwiaWF0IjoxNzU2NzgyNDUyLCJleHAiOjE3NTY4Njg4NTIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyIsImF6cCI6Ijc0REFINGpuR2pPd1RqdkExblprMGJ5cTlGRHdCcTB1In0.M5RLiSsfqeUlFPvsHQKL1uTsOxlWfyhz6zqmuiEpsMzJkvMJfcwuy5c2gF9JarV6MG_FhodWQLMVSjFpumfyJxB3z1TKZJUtndft3YCV4aVO72jRy92OD3es696wzfVvVcfk9MdZQt45ZFd31UUOI9anrYxwFAixSrvt8M7-HkcLOTEo-QYAIrTk5x2CiH1mtJZUfc1KiN6cPA6ILAWYkZ99w_a_m8HgJvI8hqAY0WMflKsio_zBwZJUpAvWYJrkga0UCbNurX7Cx1P3r9rXW0GO4yw2w4F0inh9SqLhpTPEc36sHxyUxfRlO69To3hAVP6uuH30tFWUXpkTJ9IIFA