### @name getToken
POST https://dev-6qkc8ccshfymghci.us.auth0.com/oauth/token
content-type: application/json

{
  "client_id": "74DAH4jnGjOwTjvA1nZk0byq9FDwBq0u",
  "client_secret": "QYanvgxkZf3KmJOk6cT0OhKmNVn_AehpbKVCnMnRtajIFExKarkuJnQrE-cLaEqF",
  "audience": "https://nest-demo-api",
  "grant_type": "client_credentials"
}

###

# Use access_token from the previous response
GET http://localhost:3000/protected
Accept: application/json
Authorization: Bearer {{getToken.response.body.$.access_token}}