### @name getToken
POST https://dev-6qkc8ccshfymghci.us.auth0.com/oauth/token
content-type: application/json

{
  "client_id": "74DAH4jnGjOwTjvA1nZk0byq9FDwBq0u",
  "client_secret": "QYanvgxkZf3KmJOk6cT0OhKmNVn_AehpbKVCnMnRtajIFExKarkuJnQrE-cLaEqF",
  "audience": "https://nest-demo-api",
  "grant_type": "client_credentials"
}

###

# Use access_token from the previous response
GET http://localhost:3000/protected
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImsdtpZCI6IlRIUzdCVUh4WTdDbThMUzlQU0dtdSJ9.eyJpc3MiOiJodHRwczovL2Rldi02cWtjOGNjc2hmeW1naGNpLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiI3NERBSDRqbkdqT3dUanZBMW5aazBieXE5RkR3QnEwdUBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9uZXN0LWRlbW8tYXBpIiwiaWF0IjoxNzU2MzU4MzIzLCJleHAiOjE3NTY0NDQ3MjMsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyIsImF6cCI6Ijc0REFINGpuR2pPd1RqdkExblprMGJ5cTlGRHdCcTB1In0.mRDEPN4fTy4TikXLjGEwRxh365xYogT-7JUSobuVap6vsSUkkagDW5nPl9EYXMwEpWic0AQshlDnWMvGPjpqYjM0SViSQhtPeTOi0PrInMwOupT92dXBSCI4ldTAPBYUv-0wjssGxIxs4x45STla4D3RQrHVZ3Qa-IhK3CfE1aTIU3RoaxRYWWrYlpHfHU5X2aJSXBghLc7FITCrB-RlIEbc6wAZVC9LOaCsiIpVJ87dtFsYql2Ep6AyDqRfPB7K6E4l4kgajDyi7-gpGKKq4W2cFe7hE1mB312jtM2wy6DNrRH2h4otgSTijrVUfedDDpdaZnA5EjYPAZYpEvNerA