name: Docs CI (Markdown + Spellcheck)

on:
  pull_request:
    paths: ["**/*.md"]
  push:
    branches: [main]
    paths: ["**/*.md"]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Markdown lint
      - name: markdownlint
        run: npx --yes markdownlint-cli2 "**/*.md"

      # Spell check (cspell)
      - name: cspell
        uses: streetsidesoftware/cspell-action@v6
        with:
          files: "**/*.md"
          config: "cspell.json"

